### ISSUE TITLE
How can i implement in my own friends chat sistem?

### ISSUE THREAD

**Issue by FidoAlex** [amirsanni/Video-Call-App#29]
I have my own chat sistem based on "My friends" and i have a list with online friends and i want when i click on a friend conversation to add the call functions but i don't know how to manage'it to have'it work. Can u help me pls? the conversation is with me (a) and user b (daniel) for example, and i want the room "?room=Daniel "to be created when i click user b and all the call functions to work. (The code is written in PHP + Jquery)

**Comment by amirsanni** [comment]
Hi @FidoAlex do you still need help with this?

**Comment by FidoAlex** [comment]
hi , yes im still need help with this

În joi, 16 ian. 2020 la 19:16, Amir <notifications@github.com> a scris:

**Comment by amirsanni** [comment]
The best way to approach this is to send a web socket message to the friend to initiate the call instead of creating unique rooms. 

For friend A to call friend B, you send a web socket message (a ping sort of) from A to B and once B responds, you start the call process between the two of them.

**Note**: Each friend will have unique IDs which will be mapped to all their connected socket IDs.

**Comment by FidoAlex** [comment]
im new with this can you write me an example? bcz i don't know how to
achieve this

În vin., 17 ian. 2020 la 16:19, Amir <notifications@github.com> a scris:

**Comment by amirsanni** [comment]
Oh! That's a long thing. Is your application ready?

Amir Sanni

**Comment by davedeen123** [comment]
Try twilio Click to call client...call charges will be there..but you can make call to more than 40 country. 
https://www.twilio.com/docs/voice/tutorials/click-to-call-php
